### ISSUE TITLE
How to get the coin name or coin symbol in the _succeeded response?

### ISSUE THREAD

**Issue by JTorresConsulta** [DePayFi/widgets#114]
Hi !

Is possible to get the coin name or coin symbol in the _succeeded response?

Thanks!

**Comment by 0xNe0x1** [comment]
Hi @JTorresConsulta 

Thanks for using DePay.

When you say "_succeeded" response, do you mean the API response to your backend system, or the javascript callback?

Also, are you aware that anyone could deploy a token with any coin name and symbol tricking anything you check with coin name and symbol into anything a 3rd party wants? Like deploying a token named USD Coin with "USDC" symbol.

Only token addresses are sufficient to identify tokens.

**Comment by JTorresConsulta** [comment]
Hi @0xNe0x1  

Yes I know ! I amly need the coin symbol javascript callback after the payment is success ONLY for show the transaction info to the user.

**Comment by 0xNe0x1** [comment]
Do you use payment validation (e.g. managed integrations with configured `integration: "id"`) or plain DePayWidgets.Payment with configured `accept`?

**Comment by JTorresConsulta** [comment]
This is my basic JS code: 

```
DePayWidgets.Payment({
	currency: 'USD',
	amount: {
		fix: 1,
		currency: 'USD'
	},
	accept: [
		{
			blockchain: 'gnosis',
			token: '0x9C58BAcC331c9aa871AFD802DB6379a98e80CEdb',//xDAI
			receiver: '0xf11069FAa3E382F78Aef9858a51F302709e2772C'
		}
		/*
		{
			blockchain: 'gnosis',
			token: '0x4ECaBa5870353805a9F068101A40E0f32ed605C6',//USDT
			receiver: '0xf11069FAa3E382F78Aef9858a51F302709e2772C'
		},
		{
			blockchain: 'gnosis',
			token: '0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83', //USDC
			receiver: '0xf11069FAa3E382F78Aef9858a51F302709e2772C'
		} 
		*/
	],
	succeeded: (tx)=> {
		var res = JSON.parse(JSON.stringify(tx))
 		console.log("amount: " + res.value )
		console.log("blockchain: " + res.blockchain )
		//token symbol or name ????
	}
});
```

**Comment by 0xNe0x1** [comment]
As the user could use any token to perform the payment, I need to double check if you want to display what you have received or what the user used to perform the payment?

**Comment by JTorresConsulta** [comment]
I need to know what was the coin that the user use to make the payment (for create and invoice obviously)

**Comment by 0xNe0x1** [comment]
I've added `payment` to the `succeeded` callback in v12.9.0

Check updated documentation: https://github.com/DePayFi/widgets?tab=readme-ov-file#succeeded

Feel free to leave a star 😉 ⭐  https://github.com/DePayFi/widgets

**Comment by JTorresConsulta** [comment]
Cool ! Thanks for the good support @0xNe0x1 
 
 ⭐ ⭐ ⭐ ⭐ ⭐ <3
