### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by mengqing** [DePayFi/widgets#118]
Trying to test the integration locally and is getting the CORS issue when trying to trigger the widget

Access to fetch at 'https://public.depay.com/configurations/xxxx' from origin 'http://localhost:9000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Any idea on how to solve this? Thanks

**Comment by 0xNe0x1** [comment]
can you share a screenshot of your configuration on app.depay.com?

Feel free to share via support@depay.com if you want to take this private.

**Comment by mengqing** [comment]
Hi @0xNe0x1, if you're referring to the integration configuration, I haven't made any changes to the configuration page, all I did was clicking "New Integration" and then "Payment Widget", and then used the integration ID to render the widget.

**Comment by 0xNe0x1** [comment]
Then it's raising an exception because it can render without knowing how much needs to be paid and what tokens are accepted. Obfuscated by a CORS error.

**Comment by mengqing** [comment]
After filling out the project name, the price, and the token, it started working. It would be ideal if it actually shows the relevant error, or perhaps show some warning on the configuration page, but great work!
