### ISSUE TITLE
Coinbase wallet seems to not appear as an option

### ISSUE THREAD

**Issue by mathix420** [DePayFi/widgets#44]
From https://depayfi.github.io/widgets/demo.html

Not sure if it's a bug, or a config choice.
I'm planning to use the library and was wondering why I can't pay with my coinbase wallet on your demo page.

In any case the project seems amazing, great work!

![image](https://user-images.githubusercontent.com/37625778/156221941-5941ed88-a4e3-4f8e-be32-837e82b37e4c.png)

**Comment by spape** [comment]
Sorry for the delayed reply.

It's not a bug. It's a UI/UX decision.

Currently we are auto detecting connected wallet extensions, means if you have MetaMask extension installed you will see:

<img width="511" alt="Screenshot 2022-03-07 at 10 56 32" src="https://user-images.githubusercontent.com/851393/157009485-baac467c-6af8-40e6-9367-94894f8d9a70.png">

If you do have the coinbase wallet installed (browser extension), you will see:

<img width="491" alt="Screenshot 2022-03-07 at 10 56 52" src="https://user-images.githubusercontent.com/851393/157009646-552316c3-23e7-40a9-b45e-619b4dd42b6d.png">

So if you say Coinbase Wallet... do you mean the DeFi wallet or their proprietary wallet?

**Comment by spape** [comment]
Actually we might need to integrate https://walletlink.org/#/ for this.

**Comment by mathix420** [comment]
Thanks for your reply!

Yes, I meant the defi wallet on mobile, I should have been more clear.

I really think adding the wallet-link integration could be a great addition.

**Comment by spape** [comment]
Incoming...
https://github.com/DePayFi/web3-wallets/pull/5

**Comment by spape** [comment]
https://github.com/DePayFi/widgets/releases/tag/v6.23.0
<img width="653" alt="Screenshot 2022-03-28 at 16 53 53" src="https://user-images.githubusercontent.com/851393/160437687-1af10837-bb1e-4c54-97e9-0460c9c9df26.png">
<img width="1023" alt="Screenshot 2022-03-28 at 14 49 59" src="https://user-images.githubusercontent.com/851393/160437696-722b32a3-dc6a-4631-bad5-5797a8e09ae6.png">
