### ISSUE TITLE
support native coins

### ISSUE THREAD

**Issue by 7flash** [DePayFi/widgets#57]
It seems possible to configure widgets to support Wrapped Ether, Wrapped Matic.. but would be even better if  we could just process payments allowing user to choose native Ether/Matic..

**Comment by spape** [comment]
yes it is supported. `0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE` is the placeholder for the native currency of the respective blockchain.

**Comment by spape** [comment]
I suggest you use https://app.depay.fi/integrations/new where you can play around with UI configuration to see how things translate to code.
