### ISSUE TITLE
Proposal: Depay Content Bounties

### ISSUE THREAD

**Issue by ademidun** [DePayFi/widgets#59]
Summary: People create DePay tutorials and DePay pays them.

## Background

I recently [added Depay to accept payments on my website](https://atila.ca/atlas) ([github gist](https://gist.github.com/ademidun/83f478a3314d683790b20c88322ac392), [screenshot](https://i.imgur.com/jt7pLvI.png)). However, I ran into some issues:

  
1.  It originally [didn’t work](https://github.com/DePayFi/widgets/issues/46) because I was on the wrong React version ([now fixed](https://github.com/DePayFi/widgets/commit/4a219086b17e9e8a6cdeacbcaed956bfffc18c87))
    
2.  No instructions on how to trigger Depay on a React event
    

    1.  E.g. If I want to trigger Depay when I click a button
    

4.  No instructions on how to [track the payments in our backend](https://depay.fi/documentation/api#:~:text=Ensure%20user%20release/flow%20100%25)
    

    1.  E.g. How to use DePayWidgets.Payment.track and DePayWidgets.Payment.track.poll
    
    2.  How do we integrate with websockets?
    

  

Usually, when a more established software project lacks good official documentation, people will use the community tutorials. However, DePay’s nascentness means there’s currently a lack of community tutorials. Incentivising the community to create tutorials is an effective solution.

## Why This is Important

Good documentation is important for onboarding more developers unto Depay. For example, Stripe’s [great documentation](https://greeeg.com/en/issues/what-makes-stripe-api-so-great) is a big [reason](https://document360.com/blog/tear-down-of-stripe-knowledge-base) why so many developers use it for web2 payments. DePay can be the Stripe of web3 payments documentation. More tutorials makes it easier for more people to integrate DePay into their projects, which creates more material for tutorials and repeat. A powerful [flywheel effect](https://www.atlassian.com/blog/strategy/flywheel-effect-10-lessons) for getting more projects built with DePay.

## Solution

To start, the first bounty could be one on how to add DePay to a React website. It would cover the following topics:

-   How to trigger the Depay payment flow on a button click
    
-   Simple troubleshooting tips like making sure you have the correct React version
    
-   How to track the payment status from the backend
    

  

-   Blog post tutorial + Video tutorial accompanying the blog post
    
-   Optional: Twitter Thread or similar social media post summarizing the tutorial
    

  

## Examples of Past Tutorials I’ve Made

I would love to do one of these bounties. Here are some of my qualifications:

-   [How to Build a Multi-Chain NFT Marketplace](https://atila.ca/blog/tomiwa/how-to-build-a-multi-chain-nft-marketplace-on-ethereum-polygon-and-binance-smart-chain-using-solidity-react-hardhat-and-ethersjs) ([video](https://www.youtube.com/watch?v=2XLkgUvnNJo), [twitter thread](https://twitter.com/tomiwa1a/status/1533540286554513409))
    
-   [How to add Ethereum & Binance Payments w/ React and Ethers.js](https://atila.ca/blog/tomiwa/how-to-add-ethereum-and-binance-payments-to-a-react-website-with-metamask-and-ethersjs/) ([video](https://www.youtube.com/watch?v=VPo3mn9DFTk))
    

- [How to Get Paid with Crypto Scholarships and Hackathons](https://atila.ca/blog/tomiwa/travel-the-world-for-free-while-getting-paid-with-crypto-scholarships-and-hackathons) ([video](https://www.youtube.com/watch?v=_JGJHMM3Fok), [twitter thread](https://twitter.com/tomiwa1a/status/1534517805298552832), [tiktok](https://www.tiktok.com/@atila.tech/video/7108380632547446022))

**Comment by spape** [comment]
We will reopen, once we will do content bounties.
