### ISSUE TITLE
I hope Depay can support vue

### ISSUE THREAD

**Issue by suifengtec** [DePayFi/widgets#60]
I hope Depay can support vue...

**Comment by spape** [comment]
You should be able to use the bundle and open the widget in vue.

try:
```
import DePayWidgets from '@depay/widgets/umd/index.bundle'

DePayWidgets.Payment(...)
```

**Comment by spape** [comment]
We are also testing Payment links at the moment to simplify integrations. Here is an example: https://buy.depay.fi/vR4sYAjviGd6oILCOMZSy

Let me know if you want to test this and I send you a link to test it out.

**Comment by suifengtec** [comment]
> 



> You should be able to use the bundle and open the widget in vue.
> 
> try:
> 
> ```
> import DePayWidgets from '@depay/widgets/umd/index.bundle'
> 
> DePayWidgets.Payment(...)
> ```

Thank you!
`import DePayWidgets from  '@depay/widgets/dist/umd/index.bundle'`

it works fine with Vue,  do NOT the `/dist` .
