### ISSUE TITLE
Discrepancy on "Amount" showing on Depay widget

### ISSUE THREAD

**Issue by arefay** [DePayFi/widgets#63]
See the two images below. I have a Depay config with an initial $50 amount. This is displayed to the user when they first open the widget:

<img width="435" alt="Screen Shot 2022-08-15 at 11 24 15 AM" src="https://user-images.githubusercontent.com/4808749/184664805-3586c511-347a-4cde-aef1-1bfbf28dd62a.png">

Then, if they click to change the token from Ethereum to something else, it shows a different amount. See image below.

<img width="434" alt="Screen Shot 2022-08-15 at 11 24 44 AM" src="https://user-images.githubusercontent.com/4808749/184664823-aa8cea7a-b51e-40ac-9a56-626d9e0af3c1.png">

Is this a bug, or am I mis-understanding something?

**Comment by spape** [comment]
Fix incoming...

**Comment by spape** [comment]
Fixed in https://github.com/DePayFi/widgets/releases/tag/v7.15.1
