### ISSUE TITLE
Can't add callback URL to payment, transaction is stuck validating indefinitely 

### ISSUE THREAD

**Issue by liydaco** [DePayFi/widgets#79]
Hi, I have pro api membership and I'm trying to integrate dynamic 'amount' values based on my customers shopping cart value.

On localhost, the transactions validate perfectly, but when I deploy my node/express payments api the widget hangs on 'validating payment' because no callback URL gets set on the server.

Here is my code:

Fontend (React)

`let amount = () => {
    return markers.reduce((n, { ticketPrice }) => n + ticketPrice, 0);
  };

  const openPaymentWidget = async () => {
    ({ unmount } = await DePayWidgets.Payment({
      integration: "7dd5ccaa-4af1-4824-9d4f-963f1a613012",

      validated: (successful) => {
        if (successful) {
          console.log(successful);
          handleCreateEntries();
        }
      },

      sent: (transaction) => {
        if (transaction) {
          axios.post(
            "https://moby-payments-api-production.up.railway.app/track/payments",
            {
              markers,
              transaction,
            }
          );
        }
        console.log(transaction);
      },

      succeeded: (transaction) => {
        axios.post(
          "https://moby-payments-api-production.up.railway.app/track/payments",
          {
            markers,
            transaction,
          }
        );
      },

      track: {
        method: (payment) =>
          axios.post(
            "https://moby-payments-api-production.up.railway.app/track/payments/track",
            {
              payment,
            }
          ),
        // async: true,
      },

      accept: [
        {
          blockchain: "bsc",
          amount: amount(),
          token: "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d",
          receiver: "0x60C611D9F3f50a903A9ff112Eea7887B5F9b6064",
        },
        {
          blockchain: "ethereum",
          amount: amount(),
          token: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
          receiver: "0x60C611D9F3f50a903A9ff112Eea7887B5F9b6064",
        },
        {
          blockchain: "polygon",
          amount: amount(),
          token: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
          receiver: "0x60C611D9F3f50a903A9ff112Eea7887B5F9b6064",
        },
      ],
    }));
  };`

Backend express/node:

**/track/payments/track route**

`const express = require("express");
const axios = require("axios");

const router = express.Router();

const { v4: uuidv4 } = require("uuid");

let secret_id = uuidv4();

const initialResponse = async (req) => {

  let initialResponse = await axios({
    method: "post", //you can set what request you want to be
    url: "https://api.depay.com/v2/payments",
    data: {
      blockchain: req.body.payment.blockchain,
      sender: req.body.payment.sender,
      nonce: req.body.payment.nonce,
      token: req.body.payment.to_token,
      confirmations: 1,
      after_block: req.body.payment.after_block,
      callback: "https://webhook.site/1b09ce62-b3ec-4479-81f0-0442ab74b081",
      receiver: "0x60C611D9F3f50a903A9ff112Eea7887B5F9b6064",
      amount: "0.02",
      secret_id: String(secret_id),
    },
    headers: {
      "x-api-key": "lNfu1NmxQh1IphrxzVr2P10SjyghguMB9xqWk2hd",
    },
  });
  // console.log(response);

  return initialResponse.data;
};

const afterResponse = async (req) => {
  // let markers = req.body.markers;

  // let amount = markers.reduce((n, { ticketPrice }) => n + ticketPrice, 0);

  console.log(req.body);

  let afterResponse = await axios({
    method: "post", //you can set what request you want to be
    url: "https://api.depay.com/v2/payments",
    data: {
      blockchain: req.body.payment.blockchain,
      sender: req.body.payment.sender,
      nonce: req.body.payment.nonce,
      token: req.body.payment.to_token,
      confirmations: 1,
      after_block: req.body.payment.after_block,
      callback: "https://webhook.site/1b09ce62-b3ec-4479-81f0-0442ab74b081",
      receiver: "0x60C611D9F3f50a903A9ff112Eea7887B5F9b6064",
      amount: "0.02",
      transaction: req.body.payment.transaction,
      secret_id: req.body.payment.transaction,
    },
    headers: {
      "x-api-key": "API PLACEHOLDER",
    },
  });

  // console.log(afterResponse);

  return afterResponse.data;
};

router.post("/", async (req, res) => {
  if (req.body.transaction) {
    console.log(await afterResponse(req));
    console.log("after response" + afterResponse(req));
  } else {
    console.log(await initialResponse(req));
    console.log("initial response" + initialResponse(req));
  }
  console.log(req.body);
  res.json(req.body);
});

module.exports = router;
`

**/track/payments route**

`const express = require("express");
const axios = require("axios");

const { v4: uuidv4 } = require("uuid");

const router = express.Router();

const getPayment = async (req) => {
  let markers = req.body.markers;

  let amount = markers.reduce((n, { ticketPrice }) => n + ticketPrice, 0);

  // console.log(req.body);

  let response = await axios({
    method: "post", //you can set what request you want to be
    url: "https://api.depay.com/v2/payments",

    data: {
      blockchain: req.body.transaction.blockchain,
      sender: req.body.transaction.from,
      nonce: String(req.body.transaction.nonce),
      token: req.body.transaction.params.path[1],
      confirmations: 1,
      after_block: "38878507",
      callback: "https://webhook.site/1b09ce62-b3ec-4479-81f0-0442ab74b081",
      receiver: "0x60C611D9F3f50a903A9ff112Eea7887B5F9b6064",

      // amount: String(amount),
      amount: String(amount),
      transaction: req.body.transaction.id,
      secret_id: req.body.transaction.id,
    },
    headers: {
      "x-api-key": "lNfu1NmxQh1IphrxzVr2P10SjyghguMB9xqWk2hd",
    },
  });

  console.log(response);

  return response.data;
};

router.post("/", async (req, res) => {
  const update = await getPayment(req);
  console.log(update);
  res.json(update);
});

module.exports = router;
`

Everytime I check the response from the payment api the callback URL is missing. Is there an example set up that I can use for reference, I am finding the docs very confusing.

Thanks very much.

**Comment by 10xSebastian** [comment]
Can you send an email to support@depay.com 

Also to renew your api key, as it has been leaked as part of your submission.

It looks like a Backend problem submitting the correct data to the DePay API to validate the payment.
