### ISSUE TITLE
dapp in webview select metamask pay can‘t jump

### ISSUE THREAD

**Issue by qtdc1229** [DePayFi/widgets#85]
@depay/widgets

"version": "9.4.2"

when use in app’s webview can't jump wallet, but in safri is ok . either pc or mobile

https://user-images.githubusercontent.com/1852412/223636235-acf10af1-545c-48a0-85b3-3a3eeee19450.mov

**Comment by 10xSebastian** [comment]
Identified as Android only bug. iOS and Desktop are still connecting properly. We are working on a fix as we speak.

**Comment by 10xSebastian** [comment]
```
Error opening URL:  [Error: Unable to open URL: metamask://wc... Add metamask to LSApplicationQueriesSchemes in your Info.plist.]
```

**Comment by 10xSebastian** [comment]
@qtdc1229 what is the app that you are using in the demo?

**Comment by 10xSebastian** [comment]
Examples:

1. iOS -> MetaMask -> Browser -> Connect Trust Wallet
2. Android -> MetaMask -> Browser -> Connect Trust Wallet

**Comment by dingcxx** [comment]
> Examples:
> 
> 1. iOS -> MetaMask -> Browser -> Connect Trust Wallet
> 2. Android -> MetaMask -> Browser -> Connect Trust Wallet

- [ ] iOS -> MetaMask -> Browser -> Depay-> Connect Trust Wallet 
- [x] iOS -> MetaMask -> Browser -> [Walletconnect](https://walletconnect.com/)-> Connect Trust Wallet 

> ```
> Error opening URL:  [Error: Unable to open URL: metamask://wc... Add metamask to LSApplicationQueriesSchemes in your Info.plist.]
> ```

Add metamask to LSApplicationQueriesSchemes in my app Info.plist it work fine, but I need added all wallets sheme in  plist file ?


> @qtdc1229 what is the app that you are using in the demo?

hyperpay  and dapp's url is [https://rns.id](https://www.rns.id)

**Comment by 10xSebastian** [comment]
We are looking for a solution that does not force you to add it to the Info.plist.

**Comment by 10xSebastian** [comment]
@qtdc1229 & @dingcxx 

We've a demo fix ready at: https://depayfi.github.io/widgets/demo.connect.html

Can you try the following:

iOS -> Your App WebView -> https://depayfi.github.io/widgets/demo.connect.html -> Connect Trust Wallet

The demo currently only contains the fix for connecting Trust Wallet (so please do not test any other wallet at the moment).

Once you can confirm that this demo fixes your use case, we can prepare the new version (supporting all wallets on web views this way).

**Comment by 10xSebastian** [comment]
https://user-images.githubusercontent.com/851393/223706065-b5d57777-bc36-4e64-a653-21f7cbbac3d8.MP4

**Comment by dingcxx** [comment]
> @qtdc1229 & @dingcxx
> 
> We've a demo fix ready at: https://depayfi.github.io/widgets/demo.connect.html
> 
> Can you try the following:
> 
> iOS -> Your App WebView -> https://depayfi.github.io/widgets/demo.connect.html -> Connect Trust Wallet
> 
> The demo currently only contains the fix for connecting Trust Wallet (so please do not test any other wallet at the moment).
> 
> Once you can confirm that this demo fixes your use case, we can prepare the new version (supporting all wallets on web views this way).

I was try the following & result in checkbox:

- [x] iOS -> metamask -> https://depayfi.github.io/widgets/demo.connect.html -> Connect Trust Wallet
- [] iOS -> metamask -> https://depayfi.github.io/widgets/demo.connect.html -> Connect Argent Wallet
- [] iOS -> hyperpay -> https://depayfi.github.io/widgets/demo.connect.html -> Connect Trust Wallet

**Comment by 10xSebastian** [comment]
We've improved the fix and hyperpay should be covered now. Please only test Trust Wallet in hyperpay for now, as no other wallet is enabled for this new mode yet. 

Please make sure you open a new page on hyperpay (so that the new code is loaded onto hyperpay).

Once you can confirm it works for you in hyperpay, we will enable this mode for all wallets and release a new version of DePay Widgets.

**Comment by 10xSebastian** [comment]
https://user-images.githubusercontent.com/851393/223955413-de392976-9b4e-4c5e-8acc-ca83baa2bb57.mp4

**Comment by dingcxx** [comment]
- [x] iOS -> hyperpay -> https://depayfi.github.io/widgets/demo.connect.html -> Connect Trust Wallet
 - [x] iOS -> coinbase -> https://depayfi.github.io/widgets/demo.connect.html -> Connect Trust Wallet

**Comment by dingcxx** [comment]
> Perfect. So we will prepare a new version and will let you know as soon as the new version is ready (in here).

thank you so much

**Comment by 10xSebastian** [comment]
While we are completing the new version, we also added HyperPay extension detection to DePay:
![IMG_0227](https://user-images.githubusercontent.com/851393/224034356-443ecdca-92c9-4d72-8dc3-0aeca4640966.PNG)

**Comment by 10xSebastian** [comment]
v10.2.2 contains the fix:
https://github.com/DePayFi/widgets/releases/tag/v10.2.2

Please install it and give us feedback.

**Comment by dingcxx** [comment]
> v10.2.2 contains the fix: https://github.com/DePayFi/widgets/releases/tag/v10.2.2
> 
> Please install it and give us feedback.

we change to this version and test it this week, It's seem fixed. nice work ! thank you very much for your speeds

**Comment by 10xSebastian** [comment]
Recommending to go with the latest version:
https://github.com/DePayFi/widgets/releases/tag/v10.2.8

**Comment by 10xSebastian** [comment]
considering this resolved. thanks everyone.
