### ISSUE TITLE
DePay has plan to support other  platform SDK? React-Native, iOS or Android

### ISSUE THREAD

**Issue by dingcxx** [DePayFi/widgets#89]
as the title

**Comment by 10xSebastian** [comment]
Yes. We plan to eventually offer a React-Native SDK. But we can not provide any timelines for this atm.

**Comment by dingcxx** [comment]
ok, Are there any solution on React-Native ?  we need use Depay in mobile APP

**Comment by dingcxx** [comment]
I see, mybe use our web site is best solution for us, thank you
