### ISSUE TITLE
Depay how to support more chains?

### ISSUE THREAD

**Issue by dingcxx** [DePayFi/widgets#90]
Hello, our project is using Depay as the payment component for our application. Currently, the Depay documentation states that it only supports three chains: eth, bsc, polygon. Now, I would like to add support for Tron. Is it possible to do this by ourselves? Or , do you have plans to expand support for more chains?

**Comment by 10xSebastian** [comment]
Hi @dingcxx 

We have plans to extend to more chains. We have quite a list of blockchains we want to add this year. 

In this regard, we have our own priorities. Currently, TRON is not within our 1-tier priorities.

Nonetheless, you can help add support for new blockchains. 

If you look into https://github.com/DePayFi/widgets/blob/main/package.json you will see that there are a lot of underlying libraries that all come together for the payment widgets. Adding a new blockchain always starts with adding them to the lowest level of our stack:

[web3-blockchains](https://github.com/DePayFi/web3-blockchains)

[web3-mock](https://github.com/DePayFi/web3-mock)

[web3-client](https://github.com/DePayFi/web3-client)

[react-token-image](https://github.com/DePayFi/react-token-image)

[web3-tokens](https://github.com/DePayFi/web3-tokens)

[web3-wallets](https://github.com/DePayFi/web3-wallets)

[web3-exchanges](https://github.com/DePayFi/web3-exchanges)

[web3-assets](https://github.com/DePayFi/web3-assets)

[web3-payments](https://github.com/DePayFi/web3-payments)

Once support for the new blockchain is added to all underlying libraries widgets will be able to support the new blockchain.

If you currently rely on payment tracking via DePay APIs, that's obviously separate work but adding support for a new blockchain to all low-level DePay libraries is always the first step.

**Comment by dingcxx** [comment]
I understand, it seems like a huge project. There is also one question: since Tron blockchain does not support EVM, does this mean that all payment protocols have to be rewritten?

**Comment by 10xSebastian** [comment]
Yes. adding a non-evm-based blockchain is a lot of work. It's not just adding an rpc url. This is one of the main reasons we at DePay work on harmonizing various blockchains/platforms into a single Web3 Payments interface.

**Comment by qtdc1229** [comment]
It is recommended to put all configurable data in a library, otherwise modifying it will be a major project. Wagmi provides the '[references](https://github.com/wagmi-dev/references)' library to provide extensibility, so that third parties can contribute quickly. This approach may be more suitable for the current situation.

**Comment by 10xSebastian** [comment]
@qtdc1229 and your point is?

Does this not look like a configuration to you?

https://github.com/DePayFi/web3-blockchains/blob/master/src/blockchains/polygon.js
